apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app:  frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: mk-frontend:1.0.12
          imagePullPolicy: Never
          ports:
            - containerPort: 7080 #7080