apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-texttoservice
spec:
  replicas: 1  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: texttospeech-app
  template:
    metadata:
      labels:
        app: texttospeech-app
    spec:
      containers:
      - name: texttoservice
        image: mk-texttoservice:1.0.0  # Replace with your Docker image name and tag
        imagePullPolicy: Never
        ports:
        - containerPort: 8083