apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app:  translation-app
  template:
    metadata:
      labels:
        app: translation-app
    spec:
      containers:
        - name: translation
          image: mk-translation:1.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8082