apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitreader-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app:  digitreader-app
  template:
    metadata:
      labels:
        app: digitreader-app
    spec:
      containers:
        - name: digitreader
          image: mk-digit-reader:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081